# Pandas Methods Demonstration
Using tips.csv dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [5]:
df.sample(3)

     total_bill   tip   sex smoker   day    time  size
173       31.85  3.18  Male    Yes   Sun  Dinner     2
138       16.00  2.00  Male    Yes  Thur   Lunch     2
47        32.40  6.00  Male     No   Sun  Dinner     4

In [6]:
df.shape

(244, 7)

In [7]:
df.size

1708

In [8]:
df.ndim

2

In [9]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [10]:
df.dtypes

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [12]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [13]:
df.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]],
      shape=(244, 7), dtype=object)

In [14]:
df['total_bill'].dtype

dtype('float64')

In [15]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [16]:
df['day'].unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [17]:
df['day'].nunique()

4

In [18]:
df['total_bill'].mean()

np.float64(19.78594262295082)

In [19]:
df['total_bill'].max()

np.float64(50.81)

In [20]:
df['total_bill'].min()

np.float64(3.07)

In [21]:
df['total_bill'].std()

np.float64(8.902411954856856)

In [22]:
df['tip'].sum()

np.float64(731.5799999999999)

In [23]:
df['day'].mode()

0    Sat
Name: day, dtype: str

In [24]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [25]:
df.notnull().sum()

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(1)

In [27]:
df.drop_duplicates().shape

(243, 7)

In [28]:
df.sort_values(by='total_bill', ascending=False).head()

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

In [29]:
df.sort_index().head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
df.reset_index(drop=True).head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [31]:
df.select_dtypes(include=['float64'])

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [32]:
df.iloc[0, 1]

np.float64(1.01)

In [33]:
df.iat[0, 1]

np.float64(1.01)

In [34]:
df['double_tip'] = df['tip'].apply(lambda x: x*2)
df.head()

   total_bill   tip     sex smoker  day    time  size  double_tip
0       16.99  1.01  Female     No  Sun  Dinner     2        2.02
1       10.34  1.66    Male     No  Sun  Dinner     3        3.32
2       21.01  3.50    Male     No  Sun  Dinner     3        7.00
3       23.68  3.31    Male     No  Sun  Dinner     2        6.62
4       24.59  3.61  Female     No  Sun  Dinner     4        7.22

In [35]:
df.corr(numeric_only=True)

            total_bill       tip      size  double_tip
total_bill    1.000000  0.675734  0.598315    0.675734
tip           0.675734  1.000000  0.489299    1.000000
size          0.598315  0.489299  1.000000    0.489299
double_tip    0.675734  1.000000  0.489299    1.000000

In [36]:
pd.concat([df.head(2), df.tail(2)], ignore_index=True)

   total_bill   tip     sex smoker   day    time  size  double_tip
0       16.99  1.01  Female     No   Sun  Dinner     2        2.02
1       10.34  1.66    Male     No   Sun  Dinner     3        3.32
2       17.82  1.75    Male     No   Sat  Dinner     2        3.50
3       18.78  3.00  Female     No  Thur  Dinner     2        6.00

In [37]:

left = df[['sex','tip']].head(5)
right = df[['sex','total_bill']].head(5)
pd.merge(left, right, on='sex')

       sex   tip  total_bill
0   Female  1.01       16.99
1   Female  1.01       24.59
2     Male  1.66       10.34
3     Male  1.66       21.01
4     Male  1.66       23.68
5     Male  3.50       10.34
6     Male  3.50       21.01
7     Male  3.50       23.68
8     Male  3.31       10.34
9     Male  3.31       21.01
10    Male  3.31       23.68
11  Female  3.61       16.99
12  Female  3.61       24.59

In [38]:

df['fake_date'] = pd.to_datetime('2025-01-01')
df[['fake_date']].head()

   fake_date
0 2025-01-01
1 2025-01-01
2 2025-01-01
3 2025-01-01
4 2025-01-01

In [39]:
df['tip'].min()

np.float64(1.0)