In [1]:
import pandas as pd

In [2]:
#Load data

df = pd.read_csv('tips.csv')

In [3]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
df.info

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [5]:
df.describe(include='all')

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [6]:
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [7]:
df.isnull().sum() #counts the total number of null values in each column

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [8]:
df[df['tip'].notnull()] #opposite of null

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:

df.dropna() #drop the missing values

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
df.ndim #shows the dimension

2

In [11]:
df.size #gives the total number of attributes

1708

In [12]:
df.columns #gives all columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [13]:
df.fillna(0) #missing values will be filled by 0

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [14]:
df.fillna(df.mean) #missing values will be filled by the mean

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
#Duplicate Data
df.duplicated().sum() #contains one duplicate data

np.int64(1)

In [16]:
df.drop_duplicates() #dropped one duplicate data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[243 rows x 7 columns]

In [17]:
# Use this instead
df.corr(numeric_only=True) #high correlation between total_bill and tip so we can remove one column

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [18]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
df[df['sex']=='Female']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [20]:
df[df['sex']=='Male'] #so males are more visitors in resturants

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [21]:
df[df['sex']=='Male'].max() #max bill and tip by a male

total_bill    50.81
tip            10.0
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              6
dtype: object

In [22]:
df[df['sex']=='Female'].max() #max bill and tip by a Female

total_bill      44.3
tip              6.5
sex           Female
smoker           Yes
day             Thur
time           Lunch
size               6
dtype: object

In [23]:
##So the max bill and tips is provided by a male

In [24]:
df[df['sex']=='Female'].min() #Min bill and tip by a Female

total_bill      3.07
tip              1.0
sex           Female
smoker            No
day              Fri
time          Dinner
size               1
dtype: object

In [25]:
df[df['sex']=='Male'].min() #Min bill and tip by a Female

total_bill      7.25
tip              1.0
sex             Male
smoker            No
day              Fri
time          Dinner
size               1
dtype: object

In [26]:
#Min bill and tip provided by a female

In [27]:
df[(df['sex']=='Female') & (df['total_bill'])].min() #Min bill and tip by a Female

total_bill      3.07
tip              1.0
sex           Female
smoker            No
day              Fri
time          Dinner
size               1
dtype: object

In [28]:
df['smoker'].count()

np.int64(244)

In [29]:
female_smokers = df[(df["smoker"] == "Yes") & (df["sex"] == 'Female')].count()
print(female_smokers.shape[0])  #gives total number of rows that are female and also smokers

7

In [30]:
male_smokers = df[(df["smoker"] == "Yes") & (df["sex"] == 'Male')].count()
print(male_smokers.shape[0])  #gives total number of rows that are male and also smokers

7

In [31]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
df[(df['time'] == 'Dinner') & (df['sex']== 'Female')] #females that go to the resturant to eat dinner

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
32        15.06  3.00  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
37        16.93  3.07  Female     No   Sat  Dinner     3
51        10.29  2.60  Female     No   Sun  Dinner     2
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
66        16.45  2.47  Female     No   Sat  Dinner     2
67         3.07  1.00  Female    Yes   Sat  Dinner     1
71        17.07  3.00  Female     No   Sat  Dinner     3
72        26.86  3.14  Female    Yes   Sat  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
74        14.73  2.20  Female     No   Sat  Dinner     2
92         5.75  1.00  Female    Yes   Fri  Dinner     2
93        16.32  4.30  Female    Yes   Fri  Dinner     2
94        22.75  3.25  Female     No   Fri  Dinner     2
100       11.35  2.50  Female    Yes   Fri  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
109       14.31  4.00  Female    Yes   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
114       25.71  4.00  Female     No   Sun  Dinner     3
115       17.31  3.50  Female     No   Sun  Dinner     2
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
158       13.39  2.61  Female     No   Sun  Dinner     2
162       16.21  2.00  Female     No   Sun  Dinner     3
164       17.51  3.00  Female    Yes   Sun  Dinner     2
168       10.59  1.61  Female    Yes   Sat  Dinner     2
169       10.63  2.00  Female    Yes   Sat  Dinner     2
178        9.60  4.00  Female    Yes   Sun  Dinner     2
186       20.90  3.50  Female    Yes   Sun  Dinner     3
188       18.15  3.50  Female    Yes   Sun  Dinner     3
209       12.76  2.23  Female    Yes   Sat  Dinner     2
213       13.27  2.50  Female    Yes   Sat  Dinner     2
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [33]:
df[df['sex'] == 'Female'].sort_values(by = 'total_bill' , ascending = True) #ascending order of total bill spent by females

     total_bill   tip     sex smoker   day    time  size
67         3.07  1.00  Female    Yes   Sat  Dinner     1
92         5.75  1.00  Female    Yes   Fri  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
145        8.35  1.50  Female     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
..          ...   ...     ...    ...   ...     ...   ...
85        34.83  5.17  Female     No  Thur   Lunch     4
11        35.26  5.00  Female     No   Sun  Dinner     4
238       35.83  4.67  Female     No   Sat  Dinner     3
197       43.11  5.00  Female    Yes  Thur   Lunch     4
102       44.30  2.50  Female    Yes   Sat  Dinner     3

[87 rows x 7 columns]

In [35]:
df[df['sex'] == 'Male'].sort_values(by = 'total_bill' , ascending = True) #ascending order of total bill spent by males

     total_bill    tip   sex smoker   day    time  size
172        7.25   5.15  Male    Yes   Sun  Dinner     2
149        7.51   2.00  Male     No  Thur   Lunch     2
195        7.56   1.44  Male     No  Thur   Lunch     2
218        7.74   1.44  Male    Yes   Sat  Dinner     2
126        8.52   1.48  Male     No  Thur   Lunch     2
..          ...    ...   ...    ...   ...     ...   ...
182       45.35   3.50  Male    Yes   Sun  Dinner     3
156       48.17   5.00  Male     No   Sun  Dinner     6
59        48.27   6.73  Male     No   Sat  Dinner     4
212       48.33   9.00  Male     No   Sat  Dinner     4
170       50.81  10.00  Male    Yes   Sat  Dinner     3

[157 rows x 7 columns]

In [37]:
pd.to_datetime(df['Date'])

KeyError: 'Date'